# Generated by Django 2.2.2 on 2020-03-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_auto_20200327_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.CharField(default='ahoj', max_length=200),
            preserve_default=False,
        ),
    ]
